/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffddb2",
        "inverse-on-surface": "#f2f1e8",
        "surface-variant": "#e4e3da",
        "surface-container-high": "#e9e8e0",
        "primary-fixed": "#a1f4c0",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-tertiary-fixed": "#3f030a",
        "on-secondary-fixed-variant": "#624000",
        "surface-container-low": "#f5f4eb",
        "surface-bright": "#fbfaf1",
        "surface-dim": "#dbdad2",
        "surface-container-lowest": "#ffffff",
        "background": "#fbfaf1",
        "on-tertiary": "#ffffff",
        "primary-container": "#00643c",
        "tertiary-container": "#8d3e41",
        "on-secondary-container": "#6f4900",
        "secondary": "#815500",
        "primary": "#004a2b",
        "surface-container": "#efeee5",
        "tertiary-fixed": "#ffdad9",
        "on-tertiary-container": "#ffbcbc",
        "surface-container-highest": "#e4e3da",
        "error": "#ba1a1a",
        "inverse-surface": "#30312b",
        "surface-tint": "#116c43",
        "on-secondary": "#ffffff",
        "outline": "#6f7a71",
        "on-surface": "#1b1c17",
        "secondary-container": "#fcb748",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb94c",
        "on-surface-variant": "#3f4942",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#fbfaf1",
        "primary-fixed-dim": "#85d8a6",
        "on-background": "#1b1c17",
        "on-error-container": "#93000a",
        "outline-variant": "#bec9bf",
        "inverse-primary": "#85d8a6",
        "tertiary": "#6f272b",
        "on-tertiary-fixed-variant": "#792e32",
        "on-primary-fixed-variant": "#005230",
        "on-secondary-fixed": "#291800",
        "on-primary-fixed": "#002110",
        "on-primary-container": "#8bdeab",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "brand": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Rammetto One", "cursive"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      screens: {
        "2xl": "1536px",
      },
    },
  },
  plugins: [],
}
