INSERT INTO public.coupons (
  code,
  display_name,
  description,
  type,
  status,
  discount_amount,
  discount_percentage,
  max_discount_amount,
  minimum_cart_value,
  valid_from,
  valid_till,
  max_uses,
  max_uses_per_user,
  is_stackable
)
VALUES
  (
    'WELCOME100',
    'Welcome Offer',
    'Flat Rs.100 off on first purchase above Rs.999',
    'FIXED',
    'active',
    100,
    NULL,
    NULL,
    999,
    now() - interval '1 day',
    now() + interval '120 day',
    10000,
    1,
    false
  ),
  (
    'FREESHIP',
    'Free Shipping',
    'Free shipping above Rs.799 cart value',
    'FREE_SHIPPING',
    'active',
    NULL,
    NULL,
    NULL,
    799,
    now() - interval '1 day',
    now() + interval '180 day',
    NULL,
    3,
    true
  ),
  (
    'SAVE10',
    'Save 10%',
    'Get 10% off, up to Rs.250, above Rs.1200',
    'PERCENTAGE',
    'active',
    NULL,
    10,
    250,
    1200,
    now() - interval '1 day',
    now() + interval '90 day',
    NULL,
    5,
    true
  ),
  (
    'HERITAGE200',
    'Heritage Special',
    'Flat Rs.200 off on high-value carts',
    'FIXED',
    'active',
    200,
    NULL,
    NULL,
    2000,
    now() - interval '1 day',
    now() + interval '60 day',
    5000,
    2,
    false
  )
ON CONFLICT (code)
DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  discount_amount = EXCLUDED.discount_amount,
  discount_percentage = EXCLUDED.discount_percentage,
  max_discount_amount = EXCLUDED.max_discount_amount,
  minimum_cart_value = EXCLUDED.minimum_cart_value,
  valid_from = EXCLUDED.valid_from,
  valid_till = EXCLUDED.valid_till,
  max_uses = EXCLUDED.max_uses,
  max_uses_per_user = EXCLUDED.max_uses_per_user,
  is_stackable = EXCLUDED.is_stackable,
  updated_at = now();;
