-- Velocity Orchestrator support tables/columns

ALTER TABLE public.seller_pickup_locations
  ADD COLUMN IF NOT EXISTS velocity_warehouse_id text,
  ADD COLUMN IF NOT EXISTS velocity_warehouse_raw jsonb,
  ADD COLUMN IF NOT EXISTS velocity_warehouse_synced_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_seller_pickup_locations_velocity_warehouse_id
  ON public.seller_pickup_locations (velocity_warehouse_id)
  WHERE velocity_warehouse_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.velocity_token_cache (
  cache_key text PRIMARY KEY,
  token text NOT NULL,
  expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.velocity_api_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  request_payload jsonb,
  response_payload jsonb,
  status_code int,
  success boolean NOT NULL DEFAULT false,
  error_message text,
  order_id uuid,
  seller_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_velocity_api_logs_action_created_at
  ON public.velocity_api_logs (action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_velocity_api_logs_order_id
  ON public.velocity_api_logs (order_id)
  WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_velocity_api_logs_seller_id
  ON public.velocity_api_logs (seller_id)
  WHERE seller_id IS NOT NULL;;
