/*\n  # Optimize RLS Policies for Performance\n\n  1. Problem\n    - RLS policies using auth.<function>() directly re-evaluate for each row\n    - Multiple permissive policies for same actions on profiles table\n    - Functions with mutable search_path\n\n  2. Solution\n    - Wrap auth.<function>() calls in (select ...) for single evaluation\n    - Remove duplicate policies\n    - Fix function search paths\n\n  3. Tables affected\n    - profiles\n    - products\n    - orders\n    - order_items\n    - addresses\n    - wishlists\n*/\n\n-- =====================\n-- Fix is_admin() function search path\n-- =====================\nCREATE OR REPLACE FUNCTION is_admin()\nRETURNS boolean\nLANGUAGE sql\nSECURITY DEFINER\nSTABLE\nSET search_path = ''\nAS $$\n  SELECT COALESCE(\n    (SELECT is_admin FROM public.profiles WHERE id = auth.uid()),\n    false\n  )\n$$;
\n\n-- =====================\n-- Fix handle_new_user function search path\n-- =====================\nCREATE OR REPLACE FUNCTION handle_new_user()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = ''\nAS $$\nBEGIN\n  INSERT INTO public.profiles (id, email, created_at, updated_at)\n  VALUES (NEW.id, NEW.email, NOW(), NOW())\n  ON CONFLICT (id) DO NOTHING;
\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- =====================\n-- Fix ensure_single_default_address function search path\n-- =====================\nCREATE OR REPLACE FUNCTION ensure_single_default_address()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = ''\nAS $$\nBEGIN\n  IF NEW.is_default = true THEN\n    UPDATE public.addresses\n    SET is_default = false\n    WHERE user_id = NEW.user_id\n      AND id != NEW.id\n      AND is_default = true;
\n  END IF;
\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- =====================\n-- PROFILES TABLE\n-- =====================\nDROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can read own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can view own profile" ON profiles;
\nDROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
\nDROP POLICY IF EXISTS "Admins can update all profiles" ON profiles;
\n\nCREATE POLICY "Users can insert own profile"\n  ON profiles FOR INSERT\n  TO authenticated\n  WITH CHECK (id = (select auth.uid()));
\n\nCREATE POLICY "Users can view own profile"\n  ON profiles FOR SELECT\n  TO authenticated\n  USING (id = (select auth.uid()) OR is_admin() = true);
\n\nCREATE POLICY "Users can update own profile"\n  ON profiles FOR UPDATE\n  TO authenticated\n  USING (id = (select auth.uid()) OR is_admin() = true)\n  WITH CHECK (id = (select auth.uid()) OR is_admin() = true);
\n\n-- =====================\n-- PRODUCTS TABLE\n-- =====================\nDROP POLICY IF EXISTS "Anyone can view active products" ON products;
\nDROP POLICY IF EXISTS "Admins can insert products" ON products;
\nDROP POLICY IF EXISTS "Admins can update products" ON products;
\nDROP POLICY IF EXISTS "Admins can delete products" ON products;
\n\nCREATE POLICY "Anyone can view active products"\n  ON products FOR SELECT\n  USING (is_active = true OR is_admin() = true);
\n\nCREATE POLICY "Admins can insert products"\n  ON products FOR INSERT\n  TO authenticated\n  WITH CHECK (is_admin() = true);
\n\nCREATE POLICY "Admins can update products"\n  ON products FOR UPDATE\n  TO authenticated\n  USING (is_admin() = true)\n  WITH CHECK (is_admin() = true);
\n\nCREATE POLICY "Admins can delete products"\n  ON products FOR DELETE\n  TO authenticated\n  USING (is_admin() = true);
\n\n-- =====================\n-- ORDERS TABLE\n-- =====================\nDROP POLICY IF EXISTS "Users can view own orders or admins can view all" ON orders;
\nDROP POLICY IF EXISTS "Authenticated users can create orders" ON orders;
\nDROP POLICY IF EXISTS "Admins can update orders" ON orders;
\nDROP POLICY IF EXISTS "Admins can delete orders" ON orders;
\n\nCREATE POLICY "Users can view own orders or admins can view all"\n  ON orders FOR SELECT\n  TO authenticated\n  USING (user_id = (select auth.uid()) OR is_admin() = true);
\n\nCREATE POLICY "Authenticated users can create orders"\n  ON orders FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = (select auth.uid()));
\n\nCREATE POLICY "Admins can update orders"\n  ON orders FOR UPDATE\n  TO authenticated\n  USING (is_admin() = true)\n  WITH CHECK (is_admin() = true);
\n\nCREATE POLICY "Admins can delete orders"\n  ON orders FOR DELETE\n  TO authenticated\n  USING (is_admin() = true);
\n\n-- =====================\n-- ORDER_ITEMS TABLE\n-- =====================\nDROP POLICY IF EXISTS "Users can view own order items or admins can view all" ON order_items;
\nDROP POLICY IF EXISTS "Authenticated users can create order items" ON order_items;
\nDROP POLICY IF EXISTS "Admins can update order items" ON order_items;
\nDROP POLICY IF EXISTS "Admins can delete order items" ON order_items;
\n\nCREATE POLICY "Users can view own order items or admins can view all"\n  ON order_items FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM orders\n      WHERE orders.id = order_items.order_id\n      AND (orders.user_id = (select auth.uid()) OR is_admin() = true)\n    )\n  );
\n\nCREATE POLICY "Authenticated users can create order items"\n  ON order_items FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM orders\n      WHERE orders.id = order_items.order_id\n      AND orders.user_id = (select auth.uid())\n    )\n  );
\n\nCREATE POLICY "Admins can update order items"\n  ON order_items FOR UPDATE\n  TO authenticated\n  USING (is_admin() = true)\n  WITH CHECK (is_admin() = true);
\n\nCREATE POLICY "Admins can delete order items"\n  ON order_items FOR DELETE\n  TO authenticated\n  USING (is_admin() = true);
\n\n-- =====================\n-- ADDRESSES TABLE\n-- =====================\nDROP POLICY IF EXISTS "Users can view own addresses" ON addresses;
\nDROP POLICY IF EXISTS "Users can insert own addresses" ON addresses;
\nDROP POLICY IF EXISTS "Users can update own addresses" ON addresses;
\nDROP POLICY IF EXISTS "Users can delete own addresses" ON addresses;
\n\nCREATE POLICY "Users can view own addresses"\n  ON addresses FOR SELECT\n  TO authenticated\n  USING (user_id = (select auth.uid()));
\n\nCREATE POLICY "Users can insert own addresses"\n  ON addresses FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = (select auth.uid()));
\n\nCREATE POLICY "Users can update own addresses"\n  ON addresses FOR UPDATE\n  TO authenticated\n  USING (user_id = (select auth.uid()))\n  WITH CHECK (user_id = (select auth.uid()));
\n\nCREATE POLICY "Users can delete own addresses"\n  ON addresses FOR DELETE\n  TO authenticated\n  USING (user_id = (select auth.uid()));
\n\n-- =====================\n-- WISHLISTS TABLE\n-- =====================\nDROP POLICY IF EXISTS "Users can view own wishlist" ON wishlists;
\nDROP POLICY IF EXISTS "Users can add to own wishlist" ON wishlists;
\nDROP POLICY IF EXISTS "Users can remove from own wishlist" ON wishlists;
\n\nCREATE POLICY "Users can view own wishlist"\n  ON wishlists FOR SELECT\n  TO authenticated\n  USING (user_id = (select auth.uid()) OR is_admin() = true);
\n\nCREATE POLICY "Users can add to own wishlist"\n  ON wishlists FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = (select auth.uid()));
\n\nCREATE POLICY "Users can remove from own wishlist"\n  ON wishlists FOR DELETE\n  TO authenticated\n  USING (user_id = (select auth.uid()));
\n\n-- =====================\n-- Drop unused indexes (optional cleanup)\n-- =====================\nDROP INDEX IF EXISTS idx_profiles_is_admin;
\nDROP INDEX IF EXISTS idx_products_category;
\nDROP INDEX IF EXISTS idx_products_is_active;
\nDROP INDEX IF EXISTS idx_orders_user_id;
\nDROP INDEX IF EXISTS idx_orders_status;
\nDROP INDEX IF EXISTS idx_order_items_order_id;
\nDROP INDEX IF EXISTS idx_order_items_product_id;
\nDROP INDEX IF EXISTS idx_addresses_user_id;
\nDROP INDEX IF EXISTS idx_addresses_is_default;
\nDROP INDEX IF EXISTS idx_wishlists_product_id;
\n;
